- name: Update Ubuntu
  apt:
    update_cache: yes

- name: Install Git
  apt:
    name: git

- name: Install Curl
  apt:
    name: curl

- name: Install Python PIP
  apt:
    name: python3-pip

- name: Install Virtualenv
  apt:
    name: python3-venv

- name: Update PIP to Latest Version
  command: pip3 install -U pip

- name: Install Python Virtualenvwrapper
  apt:
    name: virtualenvwrapper

- name: Install NGINX
  apt:
    name: nginx
    state: latest
