summary: Return all messages.

tags:
  - Messages

responses:
  200:
    description: "Succesful reponse"
    produces: 
      - application/json
    schema:
      type: array
      items:
        $ref: "#/definitions/Message"

definitions:
  Message:
    id: Message
    title: Message
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: "01f32c10-6d09-4145-98c5-56d4bf7c1329"
      recipient_id:
        type: string
        format: uuid
        example: "9ec44c7c-73d6-4912-8f83-ccff9834132b"
      kind:
        type: string
        enum: [Direct, Channel]
      backend_id:
        type: string
        readOnly: true
        example: "projects/instark/messages/0:154042575"
      content:
        type: string
        format: uuid
        example: "Hello World"
    required:
      - recipient_id
      - kind
      - content
